### ISSUE TITLE
Missing window border on Cinnamon DE

### ISSUE THREAD

**Issue by f1yn** [Fausto-Korpsvart/Nightfox-GTK-Theme#1]
Hey, I just started using this theme on my Fedora 36 system running the Cinnamon DE (5.2.7). Everything looks amazing! The only problem I seem to be having is that while using any of the bordered themes, I seem to be missing the highlighted border around active windows:

![Screenshot from 2022-11-09 10-14-44](https://user-images.githubusercontent.com/6565187/200868946-725fec3a-9aca-4ae9-8a4b-896cfcb24b1f.png)

Is there something I'm missing, like a missing theme application or something else that might add extra styles to the windows?

I can likely submit a patch as well, but confirmation this might be a bug would be really helpful first.

**Comment by f1yn** [comment]
No worries. I will be taking a look later this week, I've been meaning to see how Cinnamon handles stylesheets for a while now.

I'll post back once I have more information 👍🏻

**Comment by Fausto-Korpsvart** [comment]
> No worries. I will be taking a look later this week, I've been meaning to see how Cinnamon handles stylesheets for a while now.
> 
> I'll post back once I have more information 👍🏻

I've always wanted to go deeper into Cinnamon stylesheets to add more details like in Gnome, but due to lack of time I focus a bit more on Gnome, I'll be looking more into Cinnamon styles little by little to understand its behaviour.
I will also post here for when I have more information on the subject.

Thanks for reporting and for your support. }:-]

**Comment by Fausto-Korpsvart** [comment]
> So I spent a little bit of time yesterday digging. GTK-4 applications already have the rounded border applied to them (thanks Gnome? lol). However on Cinnamon anything GTK-3 and under is rendered using the `metacity-theme-3` xml file.
> 
> This was a huge disappointment, as I was hoping it was as easy as applying a `border-radius` and `border`. Thankfully, this wasn't the first time I've had to deal with editing Metacity files.
> 
> ## My findings
> Rendering with Metacity is like only being allowed to draw with a ruler and a paintbrush that can draw circles and rectangles. Technically that's all one really needs to render a "close-enough" rounded corner with primitives...
> 
> ![Screenshot from 2022-11-10 10-18-11](https://user-images.githubusercontent.com/6565187/201135199-1c956903-e245-4e3c-94eb-cef368e8fa56.png)
> 
> If you look closely, you can tell it's not perfect 😂 Even with my best attempts, the positioning system Metacity uses seems to round to the nearest integer, so getting "good-enough" suddenly became "that's all you're gonna get."
> 
> **Additionally, this only works for HiDPI screens, which means that for 1x and 2x global scaling in cinnamon I would need to make two separate themes just for rounded corners 🤯**
> 
> > The reason I use Cinnamon instead of Gnome is namely it's sane HiDPI support. While I don't agree with every decision the DE makes for me, it's seem to have hit the sweet-spot for making the "2x" global scale actually look more like 150% fractional scaling on Gnome w/ Wayland. This is perfect for me because I **need** a handful of X11 apps that wont work well in Wayland, and fractional scaling on X11 in Gnome is horrible.
> 
> ## How I did it
> * First I updated the constants to make borders aware of the active/inactive color setting
> 
> ```diff
>    
>    <constant name="C_titlebar_gradient_a" value="gtk:custom(titlebar_gradient_a,shade/gtk:bg[NORMAL]/1.07)" />
>    <constant name="C_titlebar_gradient_b" value="gtk:custom(titlebar_gradient_b,gtk:bg[NORMAL])" />
> -  <constant name="C_border_focused" value="gtk:custom(wm_border_focused,shade/gtk:bg[NORMAL]/0.65)" />
> -  <constant name="C_border_unfocused" value="gtk:custom(wm_border_unfocused,shade/gtk:bg[NORMAL]/0.75)" />
> +  <constant name="C_border_focused" value="#d84f76" />
> +  <constant name="C_border_unfocused" value="#4b4673" />
>    <constant name="C_title_focused" value="gtk:custom(wm_title_focused,blend/gtk:fg[NORMAL]/gtk:bg[NORMAL]/0.3)" />
>    <constant name="C_title_focused_shadow" value="gtk:custom(wm_title_focused_shadow,shade/gtk:bg[NORMAL]/1.1)" />
>    <constant name="C_title_unfocused" value="gtk:custom(wm_title_unfocused,blend/gtk:fg[NORMAL]/gtk:bg[NORMAL]/0.6)" />
> ```
> 
> * Then I updated the frame geometry (how Metactiy sees window boundaries) to make sure that the bottom of the window did not clip into the newly made Rounded corners
> 
> ```diff
>    
> -  <frame_geometry name="normal" title_scale="medium" rounded_top_left="10" rounded_top_right="10">
> -    <distance name="left_width" value="5" />
> -    <distance name="right_width" value="5" />
> -    <distance name="bottom_height" value="5" />
> +  <frame_geometry name="normal" title_scale="medium" rounded_top_left="14" rounded_top_right="14" rounded_bottom_left="14" rounded_bottom_right="14">
> +    <distance name="left_width" value="6" />
> +    <distance name="right_width" value="6" />
> +    <distance name="bottom_height" value="6" />
>      <distance name="left_titlebar_edge" value="10" />
>      <distance name="right_titlebar_edge" value="10" />
>      <distance name="title_vertical_pad" value="6" /
> ```
> 
> * And finally, I swapped out the `draw_ops` for focused and unfocused windows to use new line widths on all sides, render a white rectangle on each corner, and then draw the window background color on top to make it appear like a rounded corner on each side.
> 
> > The main reason the corners can't be perfect is the positioning of circles seems to be based on the top left rectangular bounds of the circle, not the origin of the circle (which would have made this so much easier)
> 
> ```diff
> <draw_ops name="rounded_border_focused">
> -    <line color="C_border_focused" x1="12" y1="0" x2="width-13" y2="0" />
> -    <line color="C_border_focused" x1="0" y1="height-1" x2="width-1" y2="height-1" />
> -    <line color="C_border_focused" x1="0" y1="12" x2="0" y2="height-2" />
> -    <line color="C_border_focused" x1="width-1" y1="12" x2="width-1" y2="height-2" />
> -    <arc color="C_border_focused" x="0" y="0" width="25" height="25" start_angle="270" extent_angle="90" />
> -    <arc color="C_border_focused" x="width-26" y="0" width="25" height="25" start_angle="0" extent_angle="90" />
> -    
> -    <arc color="C_border_focused" x="0" y="0" width="25" height="25" start_angle="270" extent_angle="90" />
> -    <arc color="C_border_focused" x="width-26" y="0" width="25" height="25" start_angle="0" extent_angle="90" />
> -    <line color="C_highlight" x1="13" y1="1" x2="width - 14" y2="1" />
> -    <arc color="C_highlight" x="0" y="1" width="25" height="25" start_angle="270" extent_angle="90" />
> -    <arc color="C_highlight" x="width - 26" y="1" width="25" height="25" start_angle="0" extent_angle="90" />
> +    
> +    
> +    
> +    <line color="C_border_focused" width="2" x1="2" y1="28" x2="2" y2="height-28" />
> +        
> +    <line color="C_border_focused" width="2" x1="width-2" y1="28" x2="width-2" y2="height-28" />
> +        
> +    <line color="C_border_focused" width="2" x1="28" y1="2" x2="width-28" y2="2" />
> +    
> +    <line color="C_border_focused" width="2" x1="28" y1="height-2" x2="width-28" y2="height-2" />
> +    
> +    
> +    
> +    
> +    <rectangle color="C_border_focused" x="0" y="0" width="28" height="28" filled="true" />
> +    <arc color="C_background" x="4.5" y="4.5" width="50" height="50" start_angle="270" extent_angle="90" filled="true" />
> +    
> +    <rectangle color="C_border_focused" x="width-28" y="0" width="28" height="28" filled="true" />
> +    <arc color="C_background" x="width-4.5-50" y="4.5" width="50" height="50" start_angle="0" extent_angle="90" filled="true" />
> +    
> +    <rectangle color="C_border_focused" x="width-28" y="height-28" width="28" height="28" filled="true" />
> +    <arc color="C_background" x="width-4.5-50" y="height-4.5-50" width="50" height="50" start_angle="90" extent_angle="90" filled="true" />
> +    
> +    <rectangle color="C_border_focused" x="0" y="height-28" width="28" height="28" filled="true" />
> +    <arc color="C_background" x="4.5" y="height-4.5-50" width="50" height="50" start_angle="180" extent_angle="90" filled="true" />
>    </draw_ops>
>  
>    <draw_ops name="rounded_border_unfocused">
> -    <line color="C_border_unfocused" x1="12" y1="0" x2="width-13" y2="0" />
> -    <line color="C_border_unfocused" x1="0" y1="height-1" x2="width-1" y2="height-1" />
> -    <line color="C_border_unfocused" x1="0" y1="12" x2="0" y2="height-2" />
> -    <line color="C_border_unfocused" x1="width-1" y1="12" x2="width-1" y2="height-2" />
> -    <arc color="C_border_unfocused" x="0" y="0" width="25" height="25" start_angle="270" extent_angle="90" />
> -    <arc color="C_border_unfocused" x="width-26" y="0" width="25" height="25" start_angle="0" extent_angle="90" />
> -    
> -    <arc color="C_border_unfocused" x="0" y="0" width="25" height="25" start_angle="270" extent_angle="90" />
> -    <arc color="C_border_unfocused" x="width-26" y="0" width="25" height="25" start_angle="0" extent_angle="90" />
> -    <line color="C_highlight" x1="13" y1="1" x2="width - 14" y2="1" />
> -    <arc color="C_highlight" x="0" y="1" width="25" height="25" start_angle="270" extent_angle="90" />
> -    <arc color="C_highlight" x="width - 26" y="1" width="25" height="25" start_angle="0" extent_angle="90" />
> +    
> +    
> +    
> +    <line color="C_border_unfocused" width="2" x1="2" y1="28" x2="2" y2="height-28" />
> +        
> +    <line color="C_border_unfocused" width="2" x1="width-2" y1="28" x2="width-2" y2="height-28" />
> +        
> +    <line color="C_border_unfocused" width="2" x1="28" y1="2" x2="width-28" y2="2" />
> +    
> +    <line color="C_border_unfocused" width="2" x1="28" y1="height-2" x2="width-28" y2="height-2" />
> +    
> +    
> +    
> +    
> +    <rectangle color="C_border_unfocused" x="0" y="0" width="28" height="28" filled="true" />
> +    <arc color="C_background" x="4.5" y="4.5" width="50" height="50" start_angle="270" extent_angle="90" filled="true" />
> +    
> +    <rectangle color="C_border_unfocused" x="width-28" y="0" width="28" height="28" filled="true" />
> +    <arc color="C_background" x="width-4.5-50" y="4.5" width="50" height="50" start_angle="0" extent_angle="90" filled="true" />
> +    
> +    <rectangle color="C_border_unfocused" x="width-28" y="height-28" width="28" height="28" filled="true" />
> +    <arc color="C_background" x="width-4.5-50" y="height-4.5-50" width="50" height="50" start_angle="90" extent_angle="90" filled="true" />
> +    
> +    <rectangle color="C_border_unfocused" x="0" y="height-28" width="28" height="28" filled="true" />
> +    <arc color="C_background" x="4.5" y="height-4.5-50" width="50" height="50" start_angle="180" extent_angle="90" filled="true" />
>    </draw_ops>
> ```
> 
> ## Why I'm closing this issue
> As much as I want to make a PR that fixes this theme upstream for Cinnamon, the maintainability of adding multiple permutations of this theme just for cinnamon seems like too much work. Each global scaling factor will need their own themes as 2x global scale wont render well on 1x and e.c.t.
> 
> That said, as far as I've been able to tell, few if any Metacity themes do corners like this - so it might be worth me maintaining Cinnamon support in a fork so I can track these patches.
> 
> @Fausto-Korpsvart I appreciate you putting this theme out into the open. It's the only dark theme that aesthetically hits all the right notes for me.

Greetings, @f1yn
I'm sorry to reply until now, but I've not been very healthy in the last few days.
Anyway, I plan to pick up on Monday to review what you propose, I've had a quick look at the modifications you've made and I understand what you mean, but as I mentioned, I hope to pick up in the next few days and review in more detail and try to play around a bit to see the results.

I'm also surprised that Metacity is the one in charge of all this, I was more focused on looking at GTK3 with no results.
Luckily with GTK4 we don't have that rounded corners problem anymore, it was about time xD
Anyway, thank you very much for taking the time and sharing this information, it will surely be very helpful.

Thanks for your great contribution and support, it's this kind of details that motivate me to keep working. }:]

**Comment by f1yn** [comment]
Good news and bad news. The Fedora 37 release was a few days ago, so I was safely able to update to Cinnamon 5.4.12 from 5.2. Modern Cinnamon has completely thrown Metacity out the window, and honesty - good riddance.

The bad news is that now I'm dealing with the same bug that was reported here: https://github.com/Fausto-Korpsvart/Material-GTK-Themes/issues/1 - where the GTK stylesheet is not decorating the window border correctly. It seems to be [reverting to the base styles from the Graphite GTK theme](https://github.com/vinceliuice/Graphite-gtk-theme) (which makes sense as that's the base for most of these themes). No color states for normal GTK windows (Gnome windows are fine), and there's missing border radius on the bottom of windows.

I'm going to fork this repo and see if I can figure out over the weekend how to get the GTK theme to match whatever Gnome and/or libadwaita is doing. If it's an easy fix, I might be able to suggest a way to patch your other themes as well.

**Comment by f1yn** [comment]
How it looks on Cinnamon 5.4.12:

![Screenshot from 2022-11-19 01-32-09](https://user-images.githubusercontent.com/6565187/202837986-c5cb46ed-fd55-4256-b169-b52605b7cf7e.png)

**Comment by Fausto-Korpsvart** [comment]
> Good news and bad news. The Fedora 37 release was a few days ago, so I was safely able to update to Cinnamon 5.4.12 from 5.2. Modern Cinnamon has completely thrown Metacity out the window, and honesty - good riddance.
> 
> The bad news is that now I'm dealing with the same bug that was reported here: [Fausto-Korpsvart/Material-GTK-Themes#1](https://github.com/Fausto-Korpsvart/Material-GTK-Themes/issues/1) - where the GTK stylesheet is not decorating the window border correctly. It seems to be [reverting to the base styles from the Graphite GTK theme](https://github.com/vinceliuice/Graphite-gtk-theme) (which makes sense as that's the base for most of these themes). No color states for normal GTK windows (Gnome windows are fine), and there's missing border radius on the bottom of windows.
> 
> I'm going to fork this repo and see if I can figure out over the weekend how to get the GTK theme to match whatever Gnome and/or libadwaita is doing. If it's an easy fix, I might be able to suggest a way to patch your other themes as well.

Yes, I noticed yesterday, I reinstalled all my virtual machines and noticed that in the theme settings in Cinnamon the `Metacity` part is no longer there; which leaves us again with the border problem.

I'm also looking for a way to improve the themes for Cinnamon a bit, I think it must be in `GTK3`, as I have no news that `GTK4/Libadwaita` is already being implemented in Cinnamon.

Any news I will let you know, thanks for the support.

**Comment by f1yn** [comment]
@Fausto-Korpsvart I submitted a pull request with the fix along with my findings. I will also be looking into some sort of bash solution to see if I can maybe make it easier to port this fix to other themes.
