### ISSUE TITLE
Nightfox support for GNOME 44

### ISSUE THREAD

**Issue by D3vil0p3r** [Fausto-Korpsvart/Nightfox-GTK-Theme#3]
Hello @Fausto-Korpsvart 
the fix applied on Tokyonight and Gruvbox themes for GNOME 44, when will be applied also on Nightfox theme?

**Comment by Fausto-Korpsvart** [comment]
> Hello @Fausto-Korpsvart the fix applied on Tokyonight and Gruvbox themes for GNOME 44, when will be applied also on Nightfox theme?

I hope to be able to update it by the weekend, I'm still working on some general details of the themes, but if I manage to finish on time, it should be ready by the weekend.

**Comment by Fausto-Korpsvart** [comment]
> Hello @Fausto-Korpsvart the fix applied on Tokyonight and Gruvbox themes for GNOME 44, when will be applied also on Nightfox theme?

Nightfox theme Updated!

**Comment by D3vil0p3r** [comment]
Thank you!!! You fixed the issue! Now it works correctly!
![image](https://github.com/Fausto-Korpsvart/Nightfox-GTK-Theme/assets/83867734/18b39d76-6291-4f13-a558-1b6c67425d61)
