### ISSUE TITLE
Changing dir name Icons

### ISSUE THREAD

**Issue by D3vil0p3r** [Fausto-Korpsvart/Nightfox-GTK-Theme#4]
Hello @Fausto-Korpsvart 
sorry for this small request. To keep a standardized folder naming convention, could you please rename `Icons` folder to `icons` (so removing the uppercase letter)?

**Comment by Fausto-Korpsvart** [comment]
> Hello @Fausto-Korpsvart sorry for this small request. To keep a standardized folder naming convention, could you please rename `Icons` folder to `icons` (so removing the uppercase letter)?

Ok, I will do that, thanks for the recommendation.
