### ISSUE TITLE
bg of list pane doesn't seem right?

### ISSUE THREAD

**Issue by salverde** [Fausto-Korpsvart/Nightfox-GTK-Theme#5]
not sure if this is the correct outlet for me to submit this or not but check out the bg of my settings window. It's still dark grey. doesn't seem right... 
whats a miss? 

![image](https://github.com/Fausto-Korpsvart/Nightfox-GTK-Theme/assets/105071/1eb03546-502c-4a2d-a1ea-a86e11611dae)

same thing with nautulis file manager... Did I miss something or not install correctly?

here's everything I have installed...

![image](https://github.com/Fausto-Korpsvart/Nightfox-GTK-Theme/assets/105071/c3176c24-42a0-4f09-9159-f29c9d75dd88)

**Comment by Fausto-Korpsvart** [comment]
Hello, @salverde, I'll update the Tokyonight theme today after some fixes, try this theme to see if the problem is still there;
Nightfox will be updated as soon as possible.

Thanks for report and support.

**Comment by salverde** [comment]
@Fausto-Korpsvart well this seems to be an isolated issue here for me... bc the screenshots in the README look fine, as well as on [pling.com](https://www.pling.com/p/1929104).

https://images.pling.com/img/00/00/50/03/00/1929104/duskfox-rounded-buttons.png

which btw since I first reported this issue, I've managed to change my **WM Theme** to `Nightfox-Dusk-BL`. Hoping that was the reason for this issue. Not the case. still grey background! 

thoughts?

**Comment by salverde** [comment]
@Fausto-Korpsvart could you screenshot your dconf settings perhaps? I have a feeling my nautilus side pane isn't theming bc of a setting I have there... here is what I have

![image](https://github.com/Fausto-Korpsvart/Nightfox-GTK-Theme/assets/105071/3a725304-8b7b-41bc-8ef8-a7a3f4b76ecb)

**Comment by Fausto-Korpsvart** [comment]
@salverde, Here are my dconf settings.
Please post a screenshot of Nautilus to see what is wrong.

![dconf_setings](https://github.com/Fausto-Korpsvart/Nightfox-GTK-Theme/assets/47998118/b809ac51-a541-42eb-8d20-444052a3feab)

**Comment by salverde** [comment]
hey thanks @Fausto-Korpsvart ! Here's my nautilus & settings windows...

![image](https://github.com/Fausto-Korpsvart/Nightfox-GTK-Theme/assets/105071/1b88962f-9899-4b0c-8176-04e52ad0eca1)


**any idea why this would be happening?**

**Comment by salverde** [comment]
thoughts?

**Comment by Fausto-Korpsvart** [comment]
> thoughts?

Hello, @salverde, Sorry for the delay.

Actually this theme hasn't been updated yet, I'm working on updating the themes little by little.
You can test Tokyonight to see if this bug is still there, and as soon as possible, I will update this and the other remaining themes.

**Comment by salverde** [comment]
no worries...
If you know what is causing this or rather where in the css/theme that colors this sidepane background I could submit a PR ? do you know off hand what attributes or properties in GTK that deals with the theming of Nautilus and/or settings side pane backgrounds? @Fausto-Korpsvart
