### ISSUE TITLE
Support for GNOME 46

### ISSUE THREAD

**Issue by D3vil0p3r** [Fausto-Korpsvart/Nightfox-GTK-Theme#6]
Hello @Fausto-Korpsvart 
This theme will support GNOME 46 as done for Tokyonight and Gruvbox themes?

**Comment by Fausto-Korpsvart** [comment]
> Hello @Fausto-Korpsvart This theme will support GNOME 46 as done for Tokyonight and Gruvbox themes?

Hello, @D3vil0p3r, Yes, this day I will finish the assets and update to finish the Catppuccin theme; then I will start with Nightfox to update in the next days.

**Comment by Fausto-Korpsvart** [comment]
> Hello @Fausto-Korpsvart This theme will support GNOME 46 as done for Tokyonight and Gruvbox themes?

Hello, @D3vil0p3r, The theme is already updated, the only thing missing is to add the assets with the theme colours, I will add them when I finish them, you can test it and report any error }:]

**Comment by D3vil0p3r** [comment]
Thanks @Fausto-Korpsvart Please keep me updated.

**Comment by D3vil0p3r** [comment]
Thank you. When I back home I will test it!

**Comment by D3vil0p3r** [comment]
@Fausto-Korpsvart it is a stupid request but can you rename `Icons`directory to `icons` please?

**Comment by Fausto-Korpsvart** [comment]
> @Fausto-Korpsvart it is a stupid request but can you rename `Icons`directory to `icons` please?

Done!

**Comment by D3vil0p3r** [comment]
> > @Fausto-Korpsvart it is a stupid request but can you rename `Icons`directory to `icons` please?
> 
> Done!

Can you also remove the remaining `Icons` directory?

**Comment by D3vil0p3r** [comment]
@Fausto-Korpsvart I have a last request for you: I would like to recruit you for a small activity on making a custom GTK theme with your style. I cannot find any way to contact you in private so I preferred to write here. Are you available for this paid activity? Thanks

**Comment by Fausto-Korpsvart** [comment]
> @Fausto-Korpsvart I have a last request for you: I would like to recruit you for a small activity on making a custom GTK theme with your style. I cannot find any way to contact you in private so I preferred to write here. Are you available for this paid activity? Thanks

Greetings, @D3vil0p3r.

Sorry for taking so long to reply, I've been offline this weekend, I needed to rest.

Regarding your request, I'm going to write you to your contact email on GitHub to know more about your proposal.

I appreciate you taking into account my work with the themes for your projects.
