### ISSUE TITLE
Unexpected window behavour when using install.sh on cinnamon

### ISSUE THREAD

**Issue by luccajan** [Fausto-Korpsvart/Nightfox-GTK-Theme#7]
![image](https://github.com/Fausto-Korpsvart/Nightfox-GTK-Theme/assets/57194634/a31a1ac7-3203-4a2b-b5e5-7f61ec1c6e28)
This could be user error but it only happens with this theme.
It happens when opening the terminal, once moved, minimized/maximized or resized the window behaves as expected. popups have the same odd behavior. This happened after I installed the theme using the install.sh. I did install the dependencies (sudo apt install gtk2-engines-murrine sassc). I tried manually installing the version on Pling and that one works. I'm on Mint 21.3 Cinnamon edition.

**Comment by Fausto-Korpsvart** [comment]
@luccajan, I'm checking and I can see the error, and it's not user error; I'll fix the problem and update as soon as possible.

Thanks for the report.

**Comment by Fausto-Korpsvart** [comment]
@luccajan, the problem is fixed, I have already tested and everything works fine, you can try it and report if the error persists or if you find a new error.

Again, thanks for reporting the error.

**Comment by luccajan** [comment]
Sorry for the late response. First of all I thank you for making this awesome theme, it's the best on out there. I downloaded the theme again and this time the I got an error "'gnome-shell' not found, using styles for last gnome-shell version available." And all unfocused windows have black title bars and the focused window has a transparent one. this only happens when installing with the script and not via Pling.
![unknown](https://github.com/Fausto-Korpsvart/Nightfox-GTK-Theme/assets/57194634/800a1be7-b1b2-482f-b374-14eeaa826f2f)

**Comment by Fausto-Korpsvart** [comment]
@luccajan, could you tell me the distro you use along with the version and desktop version? Because I'm testing and everything is working normally; have you installed the dependencies mentioned in the README?

Here is a sample of the tests I am doing and there is no problem.

![LinuxMint_test](https://github.com/Fausto-Korpsvart/Nightfox-GTK-Theme/assets/47998118/e4fd0945-33b8-41de-818e-45a710a6e12e)

Regarding the warning that `Gnome Shell has not been found`, that is not an error, it is just a hint, as you do not have the Gnome Desktop installed, so you are not using Gnome Shell.

**Comment by luccajan** [comment]
Thank you for your reply. I'm using mint 21.3 with cinnamon 6.0.4. The dependencies are installed.

**Comment by luccajan** [comment]
> Thank you for your reply. I'm using mint 21.3 with cinnamon 6.0.4. The dependencies are installed.

I just wiped my themes folder tried reinstalling the theme and now it works, I'm not sure what caused the issue but it seems to be solved now.

**Comment by Fausto-Korpsvart** [comment]
> I just wiped my themes folder tried reinstalling the theme and now it works, I'm not sure what caused the issue but it seems to be solved now.

It's good to know that it's working properly, as in the tests I've done I've managed to fix the first problem you reported and then everything worked fine.
Anyway, I will check what could cause that error, I will update to the latest version of Linux Mint and Cinnamon to check that everything works fine and see how I can replicate the error, it could have been some old theme that overwrote the new theme, it is always important to have only functional themes in the `.themes` folder.

Thanks for reporting and your support.
